/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import data.disasterList;
import static screens.UserHomeScreen.fetchAndSetAllDisasterScreen;
import static screens.UserHomeScreen.fetchAndSetDisasterDetailScreen;

/**
 *
 * @author Bonifacio Ronald
 */
public class AllDisasterScreen extends javax.swing.JFrame {

    /**
     * Creates new form AllDisasterScreen
     */
    public AllDisasterScreen() {
        initComponents();
    }
    
    public static int currentPageNow = 1;
    public static int startingIndex = (currentPageNow-1)*5;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        disaster1Panel = new javax.swing.JPanel();
        disaster1Title = new javax.swing.JLabel();
        disaster1Info = new javax.swing.JLabel();
        disaster2Panel = new javax.swing.JPanel();
        disaster2Title = new javax.swing.JLabel();
        disaster2Info = new javax.swing.JLabel();
        disaster3Panel = new javax.swing.JPanel();
        disaster3Title = new javax.swing.JLabel();
        disaster3Info = new javax.swing.JLabel();
        disaster4Panel = new javax.swing.JPanel();
        disaster4Title = new javax.swing.JLabel();
        disaster4Info = new javax.swing.JLabel();
        disaster5Panel = new javax.swing.JPanel();
        disaster5Title = new javax.swing.JLabel();
        disaster5Info = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pageNumber = new javax.swing.JLabel();
        previousPage = new javax.swing.JLabel();
        nextPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(242, 243, 247));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Earthquake");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("All Disasters");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(242, 243, 247));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tsunami");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 60, -1));

        jPanel8.setBackground(new java.awt.Color(242, 243, 247));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Flood");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 50, -1));

        jPanel10.setBackground(new java.awt.Color(242, 243, 247));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Landslide");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 60, -1));

        jPanel11.setBackground(new java.awt.Color(242, 243, 247));

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Strorm");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 100));

        jPanel1.setBackground(new java.awt.Color(242, 243, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        disaster1Panel.setBackground(new java.awt.Color(255, 255, 255));
        disaster1Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disaster1PanelMouseClicked(evt);
            }
        });

        disaster1Title.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        disaster1Title.setForeground(new java.awt.Color(0, 0, 0));
        disaster1Title.setText("Landslide in Cameron Highlands");

        disaster1Info.setFont(new java.awt.Font("Corbel", 2, 12)); // NOI18N
        disaster1Info.setForeground(new java.awt.Color(102, 102, 102));
        disaster1Info.setText("Pahang | Malaysia, 2 December 2021");

        javax.swing.GroupLayout disaster1PanelLayout = new javax.swing.GroupLayout(disaster1Panel);
        disaster1Panel.setLayout(disaster1PanelLayout);
        disaster1PanelLayout.setHorizontalGroup(
            disaster1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(disaster1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disaster1Title, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(disaster1PanelLayout.createSequentialGroup()
                        .addComponent(disaster1Info, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        disaster1PanelLayout.setVerticalGroup(
            disaster1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(disaster1Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disaster1Info)
                .addGap(15, 15, 15))
        );

        jPanel1.add(disaster1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 50));

        disaster2Panel.setBackground(new java.awt.Color(255, 255, 255));
        disaster2Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disaster2PanelMouseClicked(evt);
            }
        });

        disaster2Title.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        disaster2Title.setForeground(new java.awt.Color(0, 0, 0));
        disaster2Title.setText("Landslide in Cameron Highlands");

        disaster2Info.setFont(new java.awt.Font("Corbel", 2, 12)); // NOI18N
        disaster2Info.setForeground(new java.awt.Color(102, 102, 102));
        disaster2Info.setText("Pahang | Malaysia, 2 December 2021");

        javax.swing.GroupLayout disaster2PanelLayout = new javax.swing.GroupLayout(disaster2Panel);
        disaster2Panel.setLayout(disaster2PanelLayout);
        disaster2PanelLayout.setHorizontalGroup(
            disaster2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(disaster2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disaster2Title, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(disaster2PanelLayout.createSequentialGroup()
                        .addComponent(disaster2Info, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        disaster2PanelLayout.setVerticalGroup(
            disaster2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(disaster2Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disaster2Info)
                .addContainerGap())
        );

        jPanel1.add(disaster2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 50));

        disaster3Panel.setBackground(new java.awt.Color(255, 255, 255));
        disaster3Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disaster3PanelMouseClicked(evt);
            }
        });

        disaster3Title.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        disaster3Title.setForeground(new java.awt.Color(0, 0, 0));
        disaster3Title.setText("Landslide in Cameron Highlands");

        disaster3Info.setFont(new java.awt.Font("Corbel", 2, 12)); // NOI18N
        disaster3Info.setForeground(new java.awt.Color(102, 102, 102));
        disaster3Info.setText("Pahang | Malaysia, 2 December 2021");

        javax.swing.GroupLayout disaster3PanelLayout = new javax.swing.GroupLayout(disaster3Panel);
        disaster3Panel.setLayout(disaster3PanelLayout);
        disaster3PanelLayout.setHorizontalGroup(
            disaster3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(disaster3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disaster3Title, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(disaster3PanelLayout.createSequentialGroup()
                        .addComponent(disaster3Info, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        disaster3PanelLayout.setVerticalGroup(
            disaster3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(disaster3Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disaster3Info)
                .addContainerGap())
        );

        jPanel1.add(disaster3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 50));

        disaster4Panel.setBackground(new java.awt.Color(255, 255, 255));
        disaster4Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disaster4PanelMouseClicked(evt);
            }
        });

        disaster4Title.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        disaster4Title.setForeground(new java.awt.Color(0, 0, 0));
        disaster4Title.setText("Landslide in Cameron Highlands");

        disaster4Info.setFont(new java.awt.Font("Corbel", 2, 12)); // NOI18N
        disaster4Info.setForeground(new java.awt.Color(102, 102, 102));
        disaster4Info.setText("Pahang | Malaysia, 2 December 2021");

        javax.swing.GroupLayout disaster4PanelLayout = new javax.swing.GroupLayout(disaster4Panel);
        disaster4Panel.setLayout(disaster4PanelLayout);
        disaster4PanelLayout.setHorizontalGroup(
            disaster4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(disaster4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disaster4Title, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(disaster4PanelLayout.createSequentialGroup()
                        .addComponent(disaster4Info, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        disaster4PanelLayout.setVerticalGroup(
            disaster4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(disaster4Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disaster4Info)
                .addContainerGap())
        );

        jPanel1.add(disaster4Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 50));

        disaster5Panel.setBackground(new java.awt.Color(255, 255, 255));
        disaster5Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disaster5PanelMouseClicked(evt);
            }
        });

        disaster5Title.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        disaster5Title.setForeground(new java.awt.Color(0, 0, 0));
        disaster5Title.setText("Landslide in Cameron Highlands");

        disaster5Info.setFont(new java.awt.Font("Corbel", 2, 12)); // NOI18N
        disaster5Info.setForeground(new java.awt.Color(102, 102, 102));
        disaster5Info.setText("Pahang | Malaysia, 2 December 2021");

        javax.swing.GroupLayout disaster5PanelLayout = new javax.swing.GroupLayout(disaster5Panel);
        disaster5Panel.setLayout(disaster5PanelLayout);
        disaster5PanelLayout.setHorizontalGroup(
            disaster5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster5PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(disaster5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disaster5Title, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(disaster5PanelLayout.createSequentialGroup()
                        .addComponent(disaster5Info, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        disaster5PanelLayout.setVerticalGroup(
            disaster5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disaster5PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(disaster5Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disaster5Info)
                .addContainerGap())
        );

        jPanel1.add(disaster5Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 50));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        pageNumber.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pageNumber.setForeground(new java.awt.Color(255, 255, 255));
        pageNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageNumber.setText("1");

        previousPage.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        previousPage.setForeground(new java.awt.Color(255, 255, 255));
        previousPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previousPage.setText("<");
        previousPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousPageMouseClicked(evt);
            }
        });

        nextPage.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        nextPage.setForeground(new java.awt.Color(255, 255, 255));
        nextPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextPage.setText(">");
        nextPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(previousPage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageNumber)
                    .addComponent(previousPage)
                    .addComponent(nextPage))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 411, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 350, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void nextPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPageMouseClicked
        // TODO add your handling code here:
        
        
        double disasterListLength = disasterList.disasterInitList.size();
        double maxPage = Math.ceil(disasterListLength/5);
        
        if(currentPageNow + 1 <= maxPage) {
            
            currentPageNow+=1;
            startingIndex = (currentPageNow-1)*5;
            UserHomeScreen.fetchAndSetAllDisasterScreen(currentPageNow);
            
            System.out.println("Current Page After Next: "+currentPageNow);
            System.out.println("Starting index After next: "+startingIndex);
        }
    }//GEN-LAST:event_nextPageMouseClicked

    private void previousPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousPageMouseClicked
        // TODO add your handling code here:
        if(currentPageNow - 1 >= 1) {
            
            currentPageNow-=1;
            startingIndex = (currentPageNow-1)*5;
            UserHomeScreen.fetchAndSetAllDisasterScreen(currentPageNow);
            
            System.out.println("Current Page After Back: "+currentPageNow);
            System.out.println("Starting index After Back: "+startingIndex);
        }
    }//GEN-LAST:event_previousPageMouseClicked

    private void disaster1PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disaster1PanelMouseClicked
        // TODO add your handling code here:
        System.out.println(startingIndex);
        if(startingIndex <= disasterList.disasterInitList.size()-1) {
            UserHomeScreen.fetchAndSetDisasterDetailScreen(startingIndex);
        }
    }//GEN-LAST:event_disaster1PanelMouseClicked

    private void disaster2PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disaster2PanelMouseClicked
        // TODO add your handling code here:
        System.out.println(startingIndex+1);
        if(startingIndex+1 <= disasterList.disasterInitList.size()-1) {
            UserHomeScreen.fetchAndSetDisasterDetailScreen(startingIndex+1);
        }
    }//GEN-LAST:event_disaster2PanelMouseClicked

    private void disaster3PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disaster3PanelMouseClicked
        // TODO add your handling code here:
        System.out.println(startingIndex+2);
        if(startingIndex+2 <= disasterList.disasterInitList.size()-1) {
            UserHomeScreen.fetchAndSetDisasterDetailScreen(startingIndex+2);
        }
    }//GEN-LAST:event_disaster3PanelMouseClicked

    private void disaster4PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disaster4PanelMouseClicked
        // TODO add your handling code here:
        System.out.println(startingIndex+3);
        if(startingIndex+3 <= disasterList.disasterInitList.size()-1) {
            UserHomeScreen.fetchAndSetDisasterDetailScreen(startingIndex+3);
        }
    }//GEN-LAST:event_disaster4PanelMouseClicked

    private void disaster5PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disaster5PanelMouseClicked
        // TODO add your handling code here:
        System.out.println(startingIndex+4);
        if(startingIndex+4 <= disasterList.disasterInitList.size()-1) {
            UserHomeScreen.fetchAndSetDisasterDetailScreen(startingIndex+4);
        }
    }//GEN-LAST:event_disaster5PanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllDisasterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllDisasterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllDisasterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllDisasterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllDisasterScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel disaster1Info;
    public static javax.swing.JPanel disaster1Panel;
    public static javax.swing.JLabel disaster1Title;
    public static javax.swing.JLabel disaster2Info;
    public static javax.swing.JPanel disaster2Panel;
    public static javax.swing.JLabel disaster2Title;
    public static javax.swing.JLabel disaster3Info;
    public static javax.swing.JPanel disaster3Panel;
    public static javax.swing.JLabel disaster3Title;
    public static javax.swing.JLabel disaster4Info;
    public static javax.swing.JPanel disaster4Panel;
    public static javax.swing.JLabel disaster4Title;
    public static javax.swing.JLabel disaster5Info;
    public static javax.swing.JPanel disaster5Panel;
    public static javax.swing.JLabel disaster5Title;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JLabel nextPage;
    public static javax.swing.JLabel pageNumber;
    public static javax.swing.JLabel previousPage;
    // End of variables declaration//GEN-END:variables
}
