/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import data.disasterList;
import static screens.UserHomeScreen.fetchAndSetAllDisasterScreen;
import static screens.UserHomeScreen.fetchAndSetDisasterDetailScreen;

/**
 *
 * @author Bonifacio Ronald
 */
public class FaqScreen extends javax.swing.JFrame {

    /**
     * Creates new form AllDisasterScreen
     */
    public FaqScreen() {
        initComponents();
    }
    
    public static int currentPageNow = 1;
    public static int startingIndex = (currentPageNow-1)*3;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        faq1Panel = new javax.swing.JPanel();
        faq1Question = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        faq1Answer = new javax.swing.JTextArea();
        faq2Panel = new javax.swing.JPanel();
        faq2Question = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        faq2Answer = new javax.swing.JTextArea();
        faq3Panel = new javax.swing.JPanel();
        faq3Question = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        faq3Answer = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        pageNumber = new javax.swing.JLabel();
        previousPage = new javax.swing.JLabel();
        nextPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("FAQs & Tips");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        jPanel1.setBackground(new java.awt.Color(242, 243, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faq1Panel.setBackground(new java.awt.Color(255, 255, 255));
        faq1Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faq1PanelMouseClicked(evt);
            }
        });

        faq1Question.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        faq1Question.setForeground(new java.awt.Color(0, 0, 0));
        faq1Question.setText("Q1. Landslide in Cameron Highlands");

        faq1Answer.setColumns(20);
        faq1Answer.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        faq1Answer.setLineWrap(true);
        faq1Answer.setRows(5);
        jScrollPane1.setViewportView(faq1Answer);

        javax.swing.GroupLayout faq1PanelLayout = new javax.swing.GroupLayout(faq1Panel);
        faq1Panel.setLayout(faq1PanelLayout);
        faq1PanelLayout.setHorizontalGroup(
            faq1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faq1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(faq1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faq1Question, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        faq1PanelLayout.setVerticalGroup(
            faq1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faq1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(faq1Question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(faq1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 130));

        faq2Panel.setBackground(new java.awt.Color(255, 255, 255));
        faq2Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faq2PanelMouseClicked(evt);
            }
        });

        faq2Question.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        faq2Question.setForeground(new java.awt.Color(0, 0, 0));
        faq2Question.setText("Q2. Landslide in Cameron Highlands");

        faq2Answer.setColumns(20);
        faq2Answer.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        faq2Answer.setLineWrap(true);
        faq2Answer.setRows(5);
        jScrollPane2.setViewportView(faq2Answer);

        javax.swing.GroupLayout faq2PanelLayout = new javax.swing.GroupLayout(faq2Panel);
        faq2Panel.setLayout(faq2PanelLayout);
        faq2PanelLayout.setHorizontalGroup(
            faq2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faq2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(faq2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faq2Question, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        faq2PanelLayout.setVerticalGroup(
            faq2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faq2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(faq2Question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(faq2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 130));

        faq3Panel.setBackground(new java.awt.Color(255, 255, 255));

        faq3Question.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        faq3Question.setForeground(new java.awt.Color(0, 0, 0));
        faq3Question.setText("Q3. Landslide in Cameron Highlands");

        faq3Answer.setColumns(20);
        faq3Answer.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        faq3Answer.setLineWrap(true);
        faq3Answer.setRows(5);
        jScrollPane3.setViewportView(faq3Answer);

        javax.swing.GroupLayout faq3PanelLayout = new javax.swing.GroupLayout(faq3Panel);
        faq3Panel.setLayout(faq3PanelLayout);
        faq3PanelLayout.setHorizontalGroup(
            faq3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faq3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(faq3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faq3Question, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        faq3PanelLayout.setVerticalGroup(
            faq3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faq3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(faq3Question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(faq3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        pageNumber.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pageNumber.setForeground(new java.awt.Color(255, 255, 255));
        pageNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageNumber.setText("1");

        previousPage.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        previousPage.setForeground(new java.awt.Color(255, 255, 255));
        previousPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previousPage.setText("<");
        previousPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousPageMouseClicked(evt);
            }
        });

        nextPage.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        nextPage.setForeground(new java.awt.Color(255, 255, 255));
        nextPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextPage.setText(">");
        nextPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(previousPage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageNumber)
                    .addComponent(previousPage)
                    .addComponent(nextPage))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 350, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void nextPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPageMouseClicked
        // TODO add your handling code here:
        double faqListLength = data.faqTipsList.faqTipsInitList.size();
        double maxPage = Math.ceil(faqListLength/3);
        System.out.println("maxpage" + maxPage);
        
        if(currentPageNow + 1 <= maxPage) {
            
            currentPageNow+=1;
            startingIndex = (currentPageNow-1)*3;
            UserHomeScreen.fetchAndSetFaqScreen(currentPageNow);
        }
    }//GEN-LAST:event_nextPageMouseClicked

    private void previousPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousPageMouseClicked
        // TODO add your handling code here:
        if(currentPageNow - 1 >= 1) {
            
            currentPageNow-=1;
            startingIndex = (currentPageNow-1)*3;
            UserHomeScreen.fetchAndSetFaqScreen(currentPageNow);
        }
    }//GEN-LAST:event_previousPageMouseClicked

    private void faq1PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faq1PanelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_faq1PanelMouseClicked

    private void faq2PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faq2PanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_faq2PanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaqScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaqScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaqScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaqScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaqScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea faq1Answer;
    public static javax.swing.JPanel faq1Panel;
    public static javax.swing.JLabel faq1Question;
    public static javax.swing.JTextArea faq2Answer;
    public static javax.swing.JPanel faq2Panel;
    public static javax.swing.JLabel faq2Question;
    public static javax.swing.JTextArea faq3Answer;
    public static javax.swing.JPanel faq3Panel;
    public static javax.swing.JLabel faq3Question;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel nextPage;
    public static javax.swing.JLabel pageNumber;
    public static javax.swing.JLabel previousPage;
    // End of variables declaration//GEN-END:variables
}
