/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import javax.swing.JOptionPane;
import java.lang.Math; 

import data.userData;
import data.disasterList;
import data.faqTipsList;
import data.newlyReportedDisastersList;
import java.awt.Color;
import models.NewlyReportedDisaster;


/**
 *
 * @author Bonifacio Ronald
 */
public class UserHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form UserHomeScreen
     */
    public UserHomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public static void fetchAndSetFaqScreen(int currentPage) {
    
        FaqScreen.currentPageNow = currentPage;
        int faqListLength = faqTipsList.faqTipsInitList.size();
        int startingIndex = (currentPage-1)*3;
        
        
        //Revert Background Color
        FaqScreen.faq1Panel.setBackground(Color.white);
        FaqScreen.faq2Panel.setBackground(Color.white);
        FaqScreen.faq3Panel.setBackground(Color.white);
        
        //Page Number
        FaqScreen.pageNumber.setText(String.valueOf(currentPage));
        
        //FAQ 1
        if(startingIndex <= faqListLength-1) {
        
            FaqScreen.faq1Question.setText(faqTipsList.faqTipsInitList.get(startingIndex).question);
            FaqScreen.faq1Answer.setText(faqTipsList.faqTipsInitList.get(startingIndex).answer);
        }
        else {
            System.out.println("startingIndex"+startingIndex);
            System.out.println("faqListLength-1"+ (faqListLength));
            FaqScreen.faq1Question.setText("");
            FaqScreen.faq1Answer.setText("");
            FaqScreen.faq1Panel.setBackground(Color.gray);
        }
        
        //FAQ 2
        if(startingIndex+1 <= faqListLength-1) {
        
            FaqScreen.faq2Question.setText(faqTipsList.faqTipsInitList.get(startingIndex+1).question);
            FaqScreen.faq2Answer.setText(faqTipsList.faqTipsInitList.get(startingIndex+1).answer);
        }
        else {
            System.out.println("startingIndex" + (startingIndex+1));
            System.out.println("faqListLength-1"+ (faqListLength));
            FaqScreen.faq2Question.setText("");
            FaqScreen.faq2Answer.setText("");
            FaqScreen.faq2Panel.setBackground(Color.gray);
        }
        
        
        //FAQ 3
        if(startingIndex+2 <= faqListLength-1) {
        
            FaqScreen.faq3Question.setText(faqTipsList.faqTipsInitList.get(startingIndex+2).question);
            FaqScreen.faq3Answer.setText(faqTipsList.faqTipsInitList.get(startingIndex+2).answer);
        }
        else {
            System.out.println("startingIndex"+(startingIndex+2));
            System.out.println("faqListLength-1"+ (faqListLength));
            FaqScreen.faq3Question.setText("");
            FaqScreen.faq3Answer.setText("");
            FaqScreen.faq3Panel.setBackground(Color.gray);
        }
    }
    
    public static void fetchAndSetAllDisasterScreen(int currentPage) {
                
        AllDisasterScreen.currentPageNow = currentPage;
        int disasterListLength = disasterList.disasterInitList.size();
        int startingIndex = (currentPage-1)*5;
        
        //Revert Background Color
        AllDisasterScreen.disaster1Panel.setBackground(Color.white);
        AllDisasterScreen.disaster2Panel.setBackground(Color.white);
        AllDisasterScreen.disaster3Panel.setBackground(Color.white);
        AllDisasterScreen.disaster4Panel.setBackground(Color.white);
        AllDisasterScreen.disaster5Panel.setBackground(Color.white);
        
        //Page Number
        AllDisasterScreen.pageNumber.setText(String.valueOf(currentPage));
        
        //Disaster 1
        if(startingIndex <= disasterListLength-1) {
        
            AllDisasterScreen.disaster1Title.setText(disasterList.disasterInitList.get(startingIndex).type);
            AllDisasterScreen.disaster1Info.setText(disasterList.disasterInitList.get(startingIndex).location + ", " + disasterList.disasterInitList.get(startingIndex).date);
        }
        else {
            
            AllDisasterScreen.disaster1Title.setText("");
            AllDisasterScreen.disaster1Info.setText("");
            AllDisasterScreen.disaster1Panel.setBackground(Color.gray);
        }
        
        //Disaster 2
        if(startingIndex+1 <= disasterListLength-1) {
        
            AllDisasterScreen.disaster2Title.setText(disasterList.disasterInitList.get(startingIndex+1).type);
            AllDisasterScreen.disaster2Info.setText(disasterList.disasterInitList.get(startingIndex+1).location + ", " + disasterList.disasterInitList.get(startingIndex+1).date);
        }
        else {
        
            AllDisasterScreen.disaster2Title.setText("");
            AllDisasterScreen.disaster2Info.setText("");
            AllDisasterScreen.disaster2Panel.setBackground(Color.gray);
        }
        
        //Disaster 3
        if(startingIndex+2 <= disasterListLength-1) {
        
            AllDisasterScreen.disaster3Title.setText(disasterList.disasterInitList.get(startingIndex+2).type);
            AllDisasterScreen.disaster3Info.setText(disasterList.disasterInitList.get(startingIndex+2).location + ", " + disasterList.disasterInitList.get(startingIndex+2).date);
        }
        else {
        
            AllDisasterScreen.disaster3Title.setText("");
            AllDisasterScreen.disaster3Info.setText("");
            AllDisasterScreen.disaster3Panel.setBackground(Color.gray);
        }
        
        //Disaster 4 
        if(startingIndex+3 <= disasterListLength-1) {
        
            AllDisasterScreen.disaster4Title.setText(disasterList.disasterInitList.get(startingIndex+3).type);
            AllDisasterScreen.disaster4Info.setText(disasterList.disasterInitList.get(startingIndex+3).location + ", " + disasterList.disasterInitList.get(startingIndex+3).date);
        }
        else {
        
            AllDisasterScreen.disaster4Title.setText("");
            AllDisasterScreen.disaster4Info.setText("");
            AllDisasterScreen.disaster4Panel.setBackground(Color.gray);
        }
 
        //Disaster 5 
        if(startingIndex+4 <= disasterListLength-1) {
        
            AllDisasterScreen.disaster5Title.setText(disasterList.disasterInitList.get(startingIndex+4).type);
            AllDisasterScreen.disaster5Info.setText(disasterList.disasterInitList.get(startingIndex+4).location + ", " + disasterList.disasterInitList.get(startingIndex+4).date);
        }
        else {
        
            AllDisasterScreen.disaster5Title.setText("");
            AllDisasterScreen.disaster5Info.setText("");
            AllDisasterScreen.disaster5Panel.setBackground(Color.gray);
        }
    }
    
    public static void fetchAndSetDisasterDetailScreen(int listIndex) {
            
        DisasterDetailScreen disasterDetailScreen = new DisasterDetailScreen();
        
        //Image
        DisasterDetailScreen.disasterDetailImage.setIcon(new javax.swing.ImageIcon(disasterList.class.getResource(disasterList.disasterInitList.get(listIndex).imageUrl_landscape)));
        
        //Title
        DisasterDetailScreen.disasterDetailType.setText("<html><p>" + disasterList.disasterInitList.get(listIndex).type + "</p></html>");
        
        //Info
        String location = disasterList.disasterInitList.get(listIndex).location;
        String date = disasterList.disasterInitList.get(listIndex).date;
        DisasterDetailScreen.disasterDetailInfo.setText(location + ", " + date);
        
        //Donation
        String currentDonationAmount = String.valueOf(disasterList.disasterInitList.get(listIndex).donationCollection);
        String donationGoalAmount = String.valueOf(disasterList.disasterInitList.get(listIndex).donationGoal);
        double donationPercentage = (disasterList.disasterInitList.get(listIndex).donationCollection/disasterList.disasterInitList.get(listIndex).donationGoal*100.00);
        String donationPercentageString = String.valueOf(Math.floor(donationPercentage));
        DisasterDetailScreen.disasterDetailDonation.setText(currentDonationAmount + " / " + donationGoalAmount +" (" + donationPercentageString + "%)"); 
        
        //Description
        String disasterDescription = disasterList.disasterInitList.get(listIndex).description;
        DisasterDetailScreen.disasterDetailDescription.setText("<html><p>"+disasterDescription+"</p></html>");
        
        //Selected Index
        DisasterDetailScreen.selectedDisasterListIndex = listIndex;
        
        disasterDetailScreen.setVisible(true);
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        backOptionButton = new javax.swing.JPopupMenu();
        menuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        userHomeScreenUserName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        seeAllDisasterIcon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPanel10 = new javax.swing.JPanel();
        recentDisaster1Image = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        recentDisaster3Image = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        recentDisaster2Image = new javax.swing.JLabel();
        recentDisaster1Title = new javax.swing.JLabel();
        recentDisaster3Title = new javax.swing.JLabel();
        recentDisaster2Title = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        seeAllDisasterText = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        usersOverview = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        browseFaqButton = new javax.swing.JPanel();
        browseFaqHeading = new javax.swing.JLabel();
        browseFaqAction = new javax.swing.JLabel();
        reportDisasterButton = new javax.swing.JPanel();
        reportNowButtonAction = new javax.swing.JLabel();
        reportNowButtonHeading = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        menuItem1.setBackground(new java.awt.Color(0, 0, 0));
        menuItem1.setFont(new java.awt.Font("Verdana", 2, 10)); // NOI18N
        menuItem1.setForeground(new java.awt.Color(0, 0, 0));
        menuItem1.setText("Return to login screen");
        menuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem1MouseClicked(evt);
            }
        });
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        backOptionButton.add(menuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Corbel Light", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Welcome, ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        userHomeScreenUserName.setBackground(new java.awt.Color(0, 0, 0));
        userHomeScreenUserName.setFont(new java.awt.Font("Corbel Light", 2, 12)); // NOI18N
        userHomeScreenUserName.setForeground(new java.awt.Color(0, 0, 0));
        userHomeScreenUserName.setText("userName");
        jPanel1.add(userHomeScreenUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("<html>Catch Up With The Most<br>Recent <font color=\"#FF3333\"><i>Disaster News.</i></font></html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, -1));

        seeAllDisasterIcon.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        seeAllDisasterIcon.setForeground(new java.awt.Color(51, 51, 51));
        seeAllDisasterIcon.setText("🔎");
        seeAllDisasterIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeAllDisasterIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seeAllDisasterIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seeAllDisasterIconMouseExited(evt);
            }
        });
        jPanel1.add(seeAllDisasterIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText(":");
        jLabel7.setComponentPopupMenu(backOptionButton);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 90));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Latest News");

        JPanel10.setBackground(new java.awt.Color(204, 204, 204));
        JPanel10.setPreferredSize(new java.awt.Dimension(100, 166));

        recentDisaster1Image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentDisaster1ImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPanel10Layout = new javax.swing.GroupLayout(JPanel10);
        JPanel10.setLayout(JPanel10Layout);
        JPanel10Layout.setHorizontalGroup(
            JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentDisaster1Image, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        JPanel10Layout.setVerticalGroup(
            JPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentDisaster1Image, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 166));

        recentDisaster3Image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentDisaster3ImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentDisaster3Image, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentDisaster3Image, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 166));

        recentDisaster2Image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentDisaster2ImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentDisaster2Image, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recentDisaster2Image, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        recentDisaster1Title.setFont(new java.awt.Font("Corbel", 3, 12)); // NOI18N
        recentDisaster1Title.setForeground(new java.awt.Color(51, 51, 51));
        recentDisaster1Title.setText("<html><div style='text-align: center;'><p>Landslide in Cameron Highlands</p></div></html>");
        recentDisaster1Title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        recentDisaster1Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentDisaster1TitleMouseClicked(evt);
            }
        });

        recentDisaster3Title.setFont(new java.awt.Font("Corbel", 3, 12)); // NOI18N
        recentDisaster3Title.setForeground(new java.awt.Color(51, 51, 51));
        recentDisaster3Title.setText("<html><div style='text-align: center;'><p>Landslide in Cameron Highlands</p></div></html>");
        recentDisaster3Title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        recentDisaster3Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentDisaster3TitleMouseClicked(evt);
            }
        });

        recentDisaster2Title.setFont(new java.awt.Font("Corbel", 3, 12)); // NOI18N
        recentDisaster2Title.setForeground(new java.awt.Color(51, 51, 51));
        recentDisaster2Title.setText("<html><div style='text-align: center;'><p>Landslide in Cameron Highlands</p></div></html>");
        recentDisaster2Title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        recentDisaster2Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentDisaster2TitleMouseClicked(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        seeAllDisasterText.setFont(new java.awt.Font("Corbel", 2, 12)); // NOI18N
        seeAllDisasterText.setForeground(new java.awt.Color(255, 51, 51));
        seeAllDisasterText.setText("See all disasters >");
        seeAllDisasterText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeAllDisasterTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seeAllDisasterTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seeAllDisasterTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(recentDisaster1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(JPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recentDisaster2Title, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recentDisaster3Title, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(seeAllDisasterText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(seeAllDisasterText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recentDisaster1Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentDisaster3Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentDisaster2Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 350, 220));

        jPanel6.setBackground(new java.awt.Color(242, 243, 247));

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Of Interest");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usersOverview.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        usersOverview.setForeground(new java.awt.Color(0, 0, 0));
        usersOverview.setText("<html><p>Do you know? You have submitted <font color=\"#FF3333\"><b>5</b></font> disaster reports and have contributed <font color=\"#FF3333\"><b>RM550</b></font> over <font color=\"#FF3333\"><b>6</b></font> donations. <b>We thank you!</b></p></html>");
        jPanel9.add(usersOverview, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/screens/userHomeScreen/userHomeScreenUpdate1Image.png"))); // NOI18N
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 100, 80));

        browseFaqButton.setBackground(new java.awt.Color(255, 255, 255));
        browseFaqButton.setPreferredSize(new java.awt.Dimension(150, 87));
        browseFaqButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browseFaqButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                browseFaqButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                browseFaqButtonMouseExited(evt);
            }
        });

        browseFaqHeading.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        browseFaqHeading.setForeground(new java.awt.Color(255, 51, 51));
        browseFaqHeading.setText("<html><div style='text-align: center;'><p>Looking For Tips On Handling Disasters?</p></div></html>");

        browseFaqAction.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        browseFaqAction.setForeground(new java.awt.Color(255, 51, 51));
        browseFaqAction.setText("BROWSE FAQS");

        javax.swing.GroupLayout browseFaqButtonLayout = new javax.swing.GroupLayout(browseFaqButton);
        browseFaqButton.setLayout(browseFaqButtonLayout);
        browseFaqButtonLayout.setHorizontalGroup(
            browseFaqButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseFaqButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browseFaqButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(browseFaqButtonLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(browseFaqAction)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(browseFaqButtonLayout.createSequentialGroup()
                        .addComponent(browseFaqHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        browseFaqButtonLayout.setVerticalGroup(
            browseFaqButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseFaqButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(browseFaqHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseFaqAction)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        reportDisasterButton.setBackground(new java.awt.Color(255, 51, 51));
        reportDisasterButton.setPreferredSize(new java.awt.Dimension(150, 87));
        reportDisasterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportButtonClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportDisasterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportDisasterButtonMouseExited(evt);
            }
        });

        reportNowButtonAction.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        reportNowButtonAction.setForeground(new java.awt.Color(255, 255, 255));
        reportNowButtonAction.setText("REPORT NOW");

        reportNowButtonHeading.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        reportNowButtonHeading.setForeground(new java.awt.Color(255, 255, 255));
        reportNowButtonHeading.setText("<html><div style='text-align: center;'><p>Experienced A New Disaster?</p></div></html>");

        javax.swing.GroupLayout reportDisasterButtonLayout = new javax.swing.GroupLayout(reportDisasterButton);
        reportDisasterButton.setLayout(reportDisasterButtonLayout);
        reportDisasterButtonLayout.setHorizontalGroup(
            reportDisasterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportDisasterButtonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(reportNowButtonAction)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(reportDisasterButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportNowButtonHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        reportDisasterButtonLayout.setVerticalGroup(
            reportDisasterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportDisasterButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportNowButtonHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportNowButtonAction)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(browseFaqButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reportDisasterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browseFaqButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportDisasterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 350, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reportButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportButtonClicked
       
       String newDisasterType = null;
       String newDisasterLocation = null;
       String newDisasterDate = null;
       String newDisasterDescription = null;
        
       JOptionPane.showMessageDialog(null, "Hi, " + userData.initUserData.name + "! Thank you for showing interest in contributing to the list of disasters. \n\nPlease click 'OK' to continue with answering some questions about the disaster."  , "Report A Disaster", 1);
       
       while(true) {
            newDisasterType = JOptionPane.showInputDialog(null, "Please enter the type of the disaster experienced (eg- Tsunami) : ", "Disaster Type", 3);
            
            if(newDisasterType.isEmpty())
               JOptionPane.showMessageDialog(null, "Please enter a valid disaster type!", "Error", 2);
            
            else 
               break;
       }
       
       while(true) {
       
           newDisasterLocation = JOptionPane.showInputDialog(null, "Please enter the location of the given "+ newDisasterType+ " (eg- Penang | Malaysia) : ", "Disaster Location", 3);
       
           if(newDisasterLocation.isEmpty())
               JOptionPane.showMessageDialog(null, "Please enter a valid disaster location!", "Error", 2);
            
            else 
               break;
       }
       
       while(true) {
       
           newDisasterDate = JOptionPane.showInputDialog(null, "Please enter the date of the "+ newDisasterType + " taken place in "+ newDisasterLocation + " (eg- 18 February 2008) : ", "Disaster Date", 3 );
       
           if(newDisasterDate.isEmpty())
               JOptionPane.showMessageDialog(null, "Please enter a valid disaster date!", "Error", 2);
            
            else 
               break;
       }
       
       while(true) {
           newDisasterDescription = JOptionPane.showInputDialog(null, "Please enter some details of the " + newDisasterType + " happened in "+ newDisasterLocation + " on " + newDisasterDate +" : ", "Title", 3);
       
           if(newDisasterDescription.isEmpty())
               JOptionPane.showMessageDialog(null, "Please enter a valid disaster description!", "Error", 2);
            
            else 
               break;
       }
       
       JOptionPane.showMessageDialog(null, "Thank you for your input!\nYour input will be verified by our admins and updated on our system shortly.", "Report A Disaster", 1);
       
       NewlyReportedDisaster userReport = new NewlyReportedDisaster(userData.initUserData.name, newDisasterType, newDisasterLocation, newDisasterDate, newDisasterDescription);
       newlyReportedDisastersList.newlyReportedDisasterList.add(userReport);
       userData.initUserData.numberOfReport++;
       
       screens.UserLoginScreen.setUserHomeScreenData();
    }//GEN-LAST:event_reportButtonClicked

    private void recentDisaster1ImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentDisaster1ImageMouseClicked
        // TODO add your handling code here:
        fetchAndSetDisasterDetailScreen(0);
    }//GEN-LAST:event_recentDisaster1ImageMouseClicked

    private void recentDisaster2ImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentDisaster2ImageMouseClicked
        // TODO add your handling code here:
        fetchAndSetDisasterDetailScreen(1);
    }//GEN-LAST:event_recentDisaster2ImageMouseClicked

    private void recentDisaster3ImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentDisaster3ImageMouseClicked
        // TODO add your handling code here:
        fetchAndSetDisasterDetailScreen(2);
    }//GEN-LAST:event_recentDisaster3ImageMouseClicked

    private void recentDisaster1TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentDisaster1TitleMouseClicked
        // TODO add your handling code here:
        fetchAndSetDisasterDetailScreen(0);
    }//GEN-LAST:event_recentDisaster1TitleMouseClicked

    private void recentDisaster2TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentDisaster2TitleMouseClicked
        // TODO add your handling code here:
        fetchAndSetDisasterDetailScreen(1);
    }//GEN-LAST:event_recentDisaster2TitleMouseClicked

    private void recentDisaster3TitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentDisaster3TitleMouseClicked
        // TODO add your handling code here:
        fetchAndSetDisasterDetailScreen(2);
    }//GEN-LAST:event_recentDisaster3TitleMouseClicked

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        // TODO add your handling code here:
        UserLoginScreen login = new UserLoginScreen();
        UserLoginScreen.allPanes.setSelectedIndex(2);
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItem1ActionPerformed

    private void menuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem1MouseClicked

    private void reportDisasterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportDisasterButtonMouseEntered
        // TODO add your handling code here:
        Color enteredPanelColor = new Color(255, 255,255);
        Color enteredTextColor = new Color(255, 51, 51);
        reportDisasterButton.setBackground(enteredPanelColor);
        reportNowButtonHeading.setForeground(enteredTextColor);
        reportNowButtonAction.setForeground(enteredTextColor);
    }//GEN-LAST:event_reportDisasterButtonMouseEntered

    private void reportDisasterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportDisasterButtonMouseExited
        // TODO add your handling code here:
        Color exitedPanelColor = new Color(255, 51, 51);
        Color exitedTextColor = new Color(255, 255, 255);
        reportDisasterButton.setBackground(exitedPanelColor);
        reportNowButtonHeading.setForeground(exitedTextColor);
        reportNowButtonAction.setForeground(exitedTextColor);
    }//GEN-LAST:event_reportDisasterButtonMouseExited

    private void browseFaqButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseFaqButtonMouseEntered
        // TODO add your handling code here:
        Color enteredPanelColor = new Color(255, 51, 51);
        Color enteredTextColor = new Color(255, 255, 255);
        browseFaqButton.setBackground(enteredPanelColor);
        browseFaqHeading.setForeground(enteredTextColor);
        browseFaqAction.setForeground(enteredTextColor);
    }//GEN-LAST:event_browseFaqButtonMouseEntered

    private void browseFaqButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseFaqButtonMouseExited
        // TODO add your handling code here:
        Color exitedPanelColor = new Color(255, 255, 255);
        Color exitedTextColor = new Color(255, 51, 51);
        browseFaqButton.setBackground(exitedPanelColor);
        browseFaqHeading.setForeground(exitedTextColor);
        browseFaqAction.setForeground(exitedTextColor);
    }//GEN-LAST:event_browseFaqButtonMouseExited

    private void seeAllDisasterTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllDisasterTextMouseClicked
        // TODO add your handling code here:
        AllDisasterScreen allDisaster = new AllDisasterScreen();
        fetchAndSetAllDisasterScreen(1);
        allDisaster.setVisible(true);
    }//GEN-LAST:event_seeAllDisasterTextMouseClicked

    private void seeAllDisasterIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllDisasterIconMouseClicked
        // TODO add your handling code here:
        AllDisasterScreen allDisaster = new AllDisasterScreen();
        fetchAndSetAllDisasterScreen(1);
        allDisaster.setVisible(true);
    }//GEN-LAST:event_seeAllDisasterIconMouseClicked

    private void seeAllDisasterTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllDisasterTextMouseEntered
        // TODO add your handling code here:
        Color enteredText = new Color(0,0,0);
        seeAllDisasterText.setForeground(enteredText);
    }//GEN-LAST:event_seeAllDisasterTextMouseEntered

    private void seeAllDisasterTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllDisasterTextMouseExited
        // TODO add your handling code here:
        Color exitedText = new Color(255,51,51);
        seeAllDisasterText.setForeground(exitedText);
    }//GEN-LAST:event_seeAllDisasterTextMouseExited

    private void seeAllDisasterIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllDisasterIconMouseEntered
        // TODO add your handling code here:
        Color enteredIcon = new Color(255,51,51);
        seeAllDisasterIcon.setForeground(enteredIcon);
    }//GEN-LAST:event_seeAllDisasterIconMouseEntered

    private void seeAllDisasterIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllDisasterIconMouseExited
        // TODO add your handling code here:
        Color exitedIcon = new Color(51,51,51);
        seeAllDisasterIcon.setForeground(exitedIcon);
    }//GEN-LAST:event_seeAllDisasterIconMouseExited

    private void browseFaqButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseFaqButtonMouseClicked
        // TODO add your handling code here:
        FaqScreen faqScreen = new FaqScreen();
        fetchAndSetFaqScreen(1);
        faqScreen.setVisible(true);
    }//GEN-LAST:event_browseFaqButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel10;
    private javax.swing.JPopupMenu backOptionButton;
    private javax.swing.JLabel browseFaqAction;
    private javax.swing.JPanel browseFaqButton;
    private javax.swing.JLabel browseFaqHeading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JMenuItem menuItem1;
    public static javax.swing.JLabel recentDisaster1Image;
    public static javax.swing.JLabel recentDisaster1Title;
    public static javax.swing.JLabel recentDisaster2Image;
    public static javax.swing.JLabel recentDisaster2Title;
    public static javax.swing.JLabel recentDisaster3Image;
    public static javax.swing.JLabel recentDisaster3Title;
    private javax.swing.JPanel reportDisasterButton;
    private javax.swing.JLabel reportNowButtonAction;
    private javax.swing.JLabel reportNowButtonHeading;
    private javax.swing.JLabel seeAllDisasterIcon;
    private javax.swing.JLabel seeAllDisasterText;
    public static javax.swing.JLabel userHomeScreenUserName;
    public static javax.swing.JLabel usersOverview;
    // End of variables declaration//GEN-END:variables
}
